name: Create Pull Request

on:
  push:
    branches:
      - staging

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0
          ref: main
      - name: Reset main branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto-merge/staging-to-main
          # token: ${{ secrets.GITHUB_TOKEN }}
          # title: 'Auto-merge staging into main'
          # body: 'Automated pull request to merge staging into main.'
          # labels: 'auto-merge'

  # wait_for_merge:
  #   needs: create_pull_request
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Wait for PR to be merged
  #       uses: lewagon/wait-on-check-action@v1.3.1
  #       with:
  #         ref: ${{ steps.create_pr.outputs.pull-request-number }}
  #         check-name: "pull-request"
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #         wait-interval: 60
